server:
  port: 8002

spring:
  application:
    name: short-link-admin
  cloud:
    nacos:
      discovery:
        server-addr: 1.92.72.62:8848
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.8.131:3306/shotlink?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      connection-test-query: select 1
#      connection-timeout: 20000
#      idle-timeout: 300000
#      maximum-pool-size: 5
#      minimum-idle: 5
  data:
    redis:
      host: 1.92.72.62
      port: 6379
      password: hexiang123321

#short-link:
#  group:
#    max-num: 20
#  flow-limit:
#    enable: true
#    time-window: 1
#    max-access-count: 20
