server:
  port: 8001

spring:
  application:
    name: short-link-project
  datasource:
    # ShardingSphere ? Driver ???????????????
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere ??????
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  cloud:
    nacos:
      discovery:
        server-addr: 1.92.72.62:8848
        username: nacos
        password: nacos
  #      username: root
#      password: root
#      url: jdbc:mysql://192.168.8.131:3306/shotlink?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      hikari:
#        connection-test-query: select 1
#        connection-timeout: 20000
#        idle-timeout: 300000
#        maximum-pool-size: 5
#        minimum-idle: 5
  data:
    redis:
      host: 1.92.72.62
      port: 6379
      password: hexiang123321


short-link:
  stats:
    locale:
      #TODO ??IP API
      amap-key: 824c511f0997586ea016f979fdb23087